sudo: required
services:
  - docker

before_install:
  - docker build -t clnarain/docker-react -f Dockerfile.Dev .

script:
  - docker run -e CI=true clnarain/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: $AZURE_WA_SITE
  verbose: true
  on:
    branch: master
