sudo: required
services:
  - docker

before_install:
  - docker build -t clnarain/docker-react -f Dockerfile.Dev .

script:
  - docker run -e CI=true clnarain/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  username: "laks"
  password: "L1fe@Sun"
  site: "https://eutx-docker-react.azurewebsites.net"
  env