#version: "3"
#services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile.Dev
#    ports:
#      - "3000:3000"
#    volumes:
#      - /home/node/app/node_modules
#      - /mnt/c/Users/csnar/WebstormProjects/DockerProjects/NodeJS/frontend:/home/node/app
#  test:
#    build:
#      context: .
#      dockerfile: Dockerfile.Dev
#    volumes:
#      - /home/node/app/node_modules
#      - /mnt/c/Users/csnar/WebstormProjects/DockerProjects/NodeJS/frontend:/home/node/app
#    command: ["npm", "run", "test"]

version: "3"
services:
  web:
    image: eutxacr.azurecr.io/dockerfrontendapp_web
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#    build:
#      context: .
#      dockerfile: Dockerfile.Dev
    ports:
      - "80:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    image: eutxacr.azurecr.io/dockerfrontendapp_tests
#    build:
#      context: .
#      dockerfile: Dockerfile.Dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
